Article-11/hello_django/hello_django/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from hello_django.views import HomeView
from hello_uptime.api.routers import uptime_router

urlpatterns = [
    path('', view=HomeView.as_view(), name='home'),
    path('palette/', include('hello_palette.urls', namespace='palette')),
    path('uptime/', include('hello_uptime.urls', namespace='uptime')),
    path('accounts/', include(('django.contrib.auth.urls', 'auth'), namespace='auth')),
    path('admin/', admin.site.urls),
    path('api/web/', include((uptime_router.urls, 'api-web'), namespace='api-web')),
    path('api/web/auth/', include('rest_framework.urls', namespace='api-auth'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Article-11/hello_django/hello_palette/urls.py
from django.urls import path
from hello_palette.views import PaletteDetailView, PaletteFormView, PaletteDeleteView

app_name = 'palette'

urlpatterns = [
    path('', view=PaletteFormView.as_view(), name='new'),
    path('<int:pk>/', view=PaletteDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', view=PaletteDeleteView.as_view(), name='delete'),
]

Article-11/hello_django/templates/palette/delete.html
{% extends 'base.html' %}

{% block title %}{{ block.super }} - Delete #{{ palette.id }}{% endblock %}

{% block content %}
    <div>
        <img src="{{ palette.image.url }}" height=250 />
    </div>

    <p>Are you sure you want to delete the image?</p>

    <form action="" method="POST">
        {% csrf_token %}
        <button type="submit">Delete</button>
        <a href="{% url 'palette:detail' palette.pk %}">Cancel</a>
    </form>
{% endblock %}

Article-11/hello_django/templates/palette/detail.html
{% extends 'base.html' %}

{% load palette_tags %}

{% block title %}{{ block.super }} - Detail #{{ palette.id }}{% endblock %}

{% block content %}
    <div>
        <img src="{{ palette.image.url }}" height="250" />
    </div>

    {% include_color_boxes palette %}

    <p>
        <a href="{% url 'palette:delete' palette.pk %}">Delete</a>
    </p>
{% endblock %}

Article-11/hello_django/templates/palette/new.html
{% extends 'base.html' %}

{% block title %}{{ block.super }} - New{% endblock %}

{% block content %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <ul>
            {{ form.as_ul }}
        </ul>
        <button type="submit">Upload</button>
    </form>
{% endblock %}