Article-11/hello_django/hello_django/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from hello_django.views import HomeView
from hello_uptime.api.routers import uptime_router

urlpatterns = [
    path('', view=HomeView.as_view(), name='home'),
    path('palette/', include('hello_palette.urls', namespace='palette')),
    path('uptime/', include('hello_uptime.urls', namespace='uptime')),
    path('accounts/', include(('django.contrib.auth.urls', 'auth'), namespace='auth')),
    path('admin/', admin.site.urls),
    path('api/web/', include((uptime_router.urls, 'api-web'), namespace='api-web')),
    path('api/web/auth/', include('rest_framework.urls', namespace='api-auth'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Article-11/hello_django/hello_uptime/urls.py
from django.urls import path
from hello_uptime.views import UptimeDashboardView

app_name = 'uptime'

urlpatterns = [
    path('', view=UptimeDashboardView.as_view(), name='dashboard'),
]

Article-11/hello_django/hello_uptime/models.py
import requests
from dateutil.relativedelta import relativedelta
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from hello_uptime.utils import MonitoringInterval, MonitorStatus


class MonitorManager(models.Manager):
    def get_available_monitors(self, urls=None):
        urls = urls or []  # it should be a list
        now = timezone.now()
        available_monitors = self.filter(is_active=True).filter(
            models.Q(checked_at__isnull=True) |
            models.Q(interval=MonitoringInterval.MIN_5,
                     checked_at__lt=now - relativedelta(seconds=MonitoringInterval.MIN_5)) |
            models.Q(interval=MonitoringInterval.MIN_30,
                     checked_at__lt=now - relativedelta(seconds=MonitoringInterval.MIN_30)) |
            models.Q(interval=MonitoringInterval.HOUR_1,
                     checked_at__lt=now - relativedelta(seconds=MonitoringInterval.HOUR_1)) |
            models.Q(interval=MonitoringInterval.HOUR_6,
                     checked_at__lt=now - relativedelta(seconds=MonitoringInterval.HOUR_6)))
        if urls:
            available_monitors = available_monitors.filter(monitor_url__in=urls)
        return available_monitors

    def get_available_urls(self, urls=None):
        available_monitors = self.get_available_monitors(urls=urls)
        return available_monitors.values_list('monitor_url', flat=True).distinct().order_by('monitor_url')

    def check_url(self, url):
        try:
            response = requests.get(url)
            status = MonitorStatus.ONLINE if response.status_code == 200 else MonitorStatus.OFFLINE
        except (requests.exceptions.SSLError, requests.exceptions.ConnectionError):
            status = MonitorStatus.OFFLINE
        monitors = self.filter(is_active=True, monitor_url=url)
        monitors.update(status=status, checked_at=timezone.now())
        return status, monitors


class Monitor(models.Model):
    user = models.ForeignKey(
        verbose_name=_("User"), to=settings.AUTH_USER_MODEL, related_name='monitors', on_delete=models.CASCADE,
        null=True)
    monitor_url = models.URLField(verbose_name=_("URL"))
    interval = models.PositiveSmallIntegerField(
        verbose_name=_("Monitoring interval"), choices=MonitoringInterval.get_choices(),
        default=MonitoringInterval.get_default())
    status = models.CharField(verbose_name=_("Status"), max_length=9, choices=MonitorStatus.get_choices(), blank=True)
    is_active = models.BooleanField(verbose_name=_("Is active?"), blank=True, default=True)
    checked_at = models.DateTimeField(verbose_name=_("Checked at"), null=True, editable=False)
    created_at = models.DateTimeField(verbose_name=_("Created at"), auto_now_add=True)

    objects = MonitorManager()

    class Meta:
        verbose_name = _("Monitor")
        verbose_name_plural = _("Monitors")
        ordering = ('-created_at',)
        unique_together = ('user', 'monitor_url')

    def __str__(self):
        return self.monitor_url

Article-11/hello_django/templates/uptime/dashboard.html
{% extends 'base.html' %}

{% load i18n static %}

{% block title %}{{ block.super }} - Uptime{% endblock %}

{% block content %}
    <form action="{% url 'uptime:dashboard' %}" method="POST">
        {% csrf_token %}
        {{ formset.management_form }}

        {% for form in formset %}
            <table class="monitor-form"{% if form.instance.pk %} id="monitor-{{ form.instance.pk }}"{% endif %}>
                <tr>
                    <th></th>
                    <td>{% blocktrans with number=forloop.counter %}Monitor {{ number }}{% endblocktrans %}</td>
                </tr>
                {% if form.instance.pk %}
                    <tr>
                        <th>{% trans "Status" %}:</th>
                        <td class="status status-{{ form.instance.status }}">
                            {{ form.instance.get_status_display }}
                        </td>
                    </tr>
                    <tr>
                        <th>{% trans "Checked at" %}:</th>
                        <td class="checked-at">
                            {{ form.instance.checked_at }}
                        </td>
                    </tr>
                {% endif %}
                {{ form.as_table }}
            </table>
        {% endfor %}
        <table class="monitor-buttons">
            <tr>
                <th></th>
                <td><button type="submit">{% trans "Save" %}</button></td>
            </tr>
        </table>
    </form>
{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script>
        helloDjango.urls['apiMonitorList'] = '{% url 'api-web:monitor-list' %}';
    </script>
    <script src="{% static 'uptime.js' %}" defer></script>
{% endblock %}