Article-11/hello_django/hello_django/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from hello_django.views import HomeView
from hello_uptime.api.routers import uptime_router

urlpatterns = [
    path('', view=HomeView.as_view(), name='home'),
    path('palette/', include('hello_palette.urls', namespace='palette')),
    path('uptime/', include('hello_uptime.urls', namespace='uptime')),
    path('accounts/', include(('django.contrib.auth.urls', 'auth'), namespace='auth')),
    path('admin/', admin.site.urls),
    path('api/web/', include((uptime_router.urls, 'api-web'), namespace='api-web')),
    path('api/web/auth/', include('rest_framework.urls', namespace='api-auth'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Article-11/hello_django/hello_palette/urls.py
from django.urls import path
from hello_palette.views import PaletteDetailView, PaletteFormView, PaletteDeleteView

app_name = 'palette'

urlpatterns = [
    path('', view=PaletteFormView.as_view(), name='new'),
    path('<int:pk>/', view=PaletteDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', view=PaletteDeleteView.as_view(), name='delete'),
]

Article-11/hello_django/hello_uptime/urls.py
from django.urls import path
from hello_uptime.views import UptimeDashboardView

app_name = 'uptime'

urlpatterns = [
    path('', view=UptimeDashboardView.as_view(), name='dashboard'),
]

Article-11/hello_django/templates/base.html
{% load i18n static %}

<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>{% block title %}Hello{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'main.css' %}">
    </head>
    <body>
        {% block header %}
            <header>
                {% if user.is_authenticated %}
                    {% blocktrans with name=user.get_full_name|default:user.username %}Hello,  {{ name }}!{% endblocktrans %}
                    <a href="{% url 'auth:logout' %}">{% trans "Log out" %}</a>
                {% else %}
                    <a href="{% url 'auth:login' %}">{% trans "Log in" %}</a>
                {% endif %}
            </header>
        {% endblock %}

        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}

        {% block content %}{% endblock %}

        {% block scripts %}
            <script>
                var helloDjango = {
                    'urls': {}
                }
            </script>
        {% endblock %}
    </body>
</html>

Article-11/hello_django/templates/home.html
{% extends 'base.html' %}

{% block title %}{{ block.super }} - Welcome{% endblock %}

{% block content %}
    <h1 class="title">Hello, Django!</h1>
    <h2 class="subtitle">Applications</h2>
    <ul class="apps">
        <li>
            <a href="{% url 'palette:new' %}">Palette</a>
        </li>
        <li>
            <a href="{% url 'uptime:dashboard' %}">Uptime</a>
        </li>
    </ul>
{% endblock %}